"""Column helpers shared across table models."""

from __future__ import annotations

import uuid

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID as PGUUID


def pk_column() -> sa.Column:
    """UUID primary key, generated by the database when absent."""
    return sa.Column(
        PGUUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
        nullable=False,
    )


def fk_column(
    target: str,
    *,
    nullable: bool = False,
    ondelete: str = "CASCADE",
    primary_key: bool = False,
    unique: bool = False,
) -> sa.Column:
    """UUID foreign key to ``target`` (e.g. ``"users.id"``)."""
    return sa.Column(
        PGUUID(as_uuid=True),
        sa.ForeignKey(target, ondelete=ondelete),
        nullable=nullable,
        primary_key=primary_key,
        unique=unique,
    )


def created_at_column() -> sa.Column:
    return sa.Column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    )


def updated_at_column() -> sa.Column:
    """Set on write by the application layer, not by a database trigger.

    Keeping this out of the database means the value always reflects a change
    the application made deliberately, and migrations stay plain DDL.
    """
    return sa.Column(
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
        nullable=False,
    )


def new_uuid() -> uuid.UUID:
    return uuid.uuid4()
